name: Done
env:
  REPO_OWNER: meroware
  REPO_NAME: example-event-dispatcher-workflows
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
on:
  repository_dispatch:
    types: [run-done]
jobs:
  done:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run Done
        run: npm run done
