name: Ping
env:
  REPO_OWNER: meroware
  REPO_NAME: example-event-dispatcher-workflows
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
on:
  # repository_dispatch:
    # types: [run-ping] Commented out since we now use all in one workflow
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run Ping
        run: npm run ping
