name: Ping
env:
  REPO_OWNER: meroware
  REPO_NAME: example-event-dispatcher-workflows
on:
  repository_dispatch:
    types: [run-ping]
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run Ping
        run: npm run ping
